server:
  port: 8081

spring:
  application:
    name: FulfillmentService

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4500